packages:
  - apps/*
  - packages/*

catalog:
  '@commitlint/cli': 20.2.0
  '@commitlint/config-conventional': 20.2.0
  '@eslint/js': ^9.39.2
  '@neondatabase/serverless': ^1.0.2
  '@next/eslint-plugin-next': ^16.1.1
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/eslint-config': ^0.3.4
  '@tanstack/react-devtools': ^0.8.4
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@tanstack/react-router': ^1.142.11
  '@tanstack/react-router-devtools': ^1.142.11
  '@tanstack/router-plugin': ^1.142.11
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.3.1
  '@types/node': ^25.0.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.45.1
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.7.1
  globals: ^16.5.0
  hono: ^4.9.12
  husky: 9.1.7
  jsdom: ^27.3.0
  lint-staged: ^16.2.7
  lucide-react: ^0.562.0
  neonctl: ^2.19.0
  prettier: 3.7.4
  react: ^19.0.0
  react-dom: ^19.0.0
  rimraf: ^6.1.2
  tailwindcss: ^4.1.18
  tsx: ^4.21.0
  turbo: ^2.7.1
  typescript: ^5.9.3
  typescript-eslint: ^8.50.1
  vite: ^7.1.11
  vitest: ^4.0.16
  web-vitals: ^5.1.0

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
